### ISSUE TITLE
Configure samples operator to point to centos streams

### ISSUE THREAD

**Issue by vrutkovs** [openshift/okd#34]
Currently samples operator assumes user has a pull secret with "redhat.io". That might not be the case for OKD, so installer should inject a custom configuration for it.

Priorities:
* Use UBI7/8 where possible
* Use centos imagestreams for the rest
* Disable imagestream if sample is not available

See https://github.com/openshift/cluster-samples-operator#configuration.

Related to https://github.com/openshift/okd/issues/7

**Comment by jomeier** [comment]
Has this issue been fixed with

https://bugzilla.redhat.com/show_bug.cgi?id=1811204

?

**Comment by pablo-ruth** [comment]
I still have the problem with beta 4:

```
apiVersion: samples.operator.openshift.io/v1
kind: Config
metadata:
  creationTimestamp: '2020-04-22T14:41:37Z'
  finalizers:
    - samples.operator.openshift.io/finalizer
  generation: 1
  name: cluster
  resourceVersion: '990593'
  selfLink: /apis/samples.operator.openshift.io/v1/configs/cluster
  uid: eb7d8f64-ad9c-4746-8a8d-5ba8a84a4e3f
spec:
  architectures:
    - x86_64
  managementState: Managed
status:
  architectures:
    - x86_64
  conditions:
    - lastTransitionTime: '2020-04-22T14:41:38Z'
      lastUpdateTime: '2020-04-22T14:41:38Z'
      status: 'True'
      type: ImportCredentialsExist
    - lastTransitionTime: '2020-04-22T14:41:43Z'
      lastUpdateTime: '2020-04-22T14:41:43Z'
      status: 'True'
      type: ConfigurationValid
    - lastTransitionTime: '2020-04-22T14:41:47Z'
      lastUpdateTime: '2020-04-24T09:14:20Z'
      message: >-
        <imagestream/jboss-eap72-openshift>Internal error occurred:
        registry.redhat.io/jboss-eap-7/eap72-openshift:latest: Get
        https://registry.redhat.io/v2/jboss-eap-7/eap72-openshift/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-eap72-openshift><imagestream/redhat-sso73-openshift>Internal
        error occurred: registry.redhat.io/redhat-sso-7/sso73-openshift:1.0: Get
        https://registry.redhat.io/v2/redhat-sso-7/sso73-openshift/manifests/1.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/redhat-sso73-openshift><imagestream/java>Internal
        error occurred:
        registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:latest: Get
        https://registry.redhat.io/v2/redhat-openjdk-18/openjdk18-openshift/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/java><imagestream/rhdm-optaweb-employee-rostering-rhel8>Internal
        error occurred:
        registry.redhat.io/rhdm-7-tech-preview/rhdm-optaweb-employee-rostering-rhel8:7.5.1:
        Get
        https://registry.redhat.io/v2/rhdm-7-tech-preview/rhdm-optaweb-employee-rostering-rhel8/manifests/7.5.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhdm-optaweb-employee-rostering-rhel8><imagestream/jboss-datagrid71-client-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datagrid-7/datagrid71-client-openshift:1.0: Get
        https://registry.redhat.io/v2/jboss-datagrid-7/datagrid71-client-openshift/manifests/1.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datagrid71-client-openshift><imagestream/php>Internal
        error occurred: registry.redhat.io/rhscl/php-73-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/php-73-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/php><imagestream/jboss-eap70-openshift>Internal
        error occurred: registry.redhat.io/jboss-eap-7/eap70-openshift:1.7: Get
        https://registry.redhat.io/v2/jboss-eap-7/eap70-openshift/manifests/1.7:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-eap70-openshift><imagestream/redis>Internal
        error occurred: registry.redhat.io/rhscl/redis-5-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/redis-5-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/redis><imagestream/jboss-amq-63>Internal
        error occurred: registry.redhat.io/jboss-amq-6/amq63-openshift:1.4: Get
        https://registry.redhat.io/v2/jboss-amq-6/amq63-openshift/manifests/1.4:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-amq-63><imagestream/rhpam-businesscentral-monitoring-rhel8>Internal
        error occurred:
        registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.5.1:
        Get
        https://registry.redhat.io/v2/rhpam-7/rhpam-businesscentral-monitoring-rhel8/manifests/7.5.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhpam-businesscentral-monitoring-rhel8><imagestream/mongodb>Internal
        error occurred: registry.redhat.io/rhscl/mongodb-36-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/mongodb-36-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/mongodb><imagestream/jboss-datagrid71-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datagrid-7/datagrid71-openshift:1.3: Get
        https://registry.redhat.io/v2/jboss-datagrid-7/datagrid71-openshift/manifests/1.3:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datagrid71-openshift><imagestream/fuse7-karaf-openshift>Internal
        error occurred: registry.redhat.io/fuse7/fuse-karaf-openshift:1.5: Get
        https://registry.redhat.io/v2/fuse7/fuse-karaf-openshift/manifests/1.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fuse7-karaf-openshift><imagestream/jboss-webserver31-tomcat8-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-webserver-3/webserver31-tomcat8-openshift:1.4:
        Get
        https://registry.redhat.io/v2/jboss-webserver-3/webserver31-tomcat8-openshift/manifests/1.4:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-webserver31-tomcat8-openshift><imagestream/mariadb>Internal
        error occurred: registry.redhat.io/rhscl/mariadb-102-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/mariadb-102-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/mariadb><imagestream/apicurito-ui>Internal
        error occurred: registry.redhat.io/fuse7/fuse-apicurito:1.5: Get
        https://registry.redhat.io/v2/fuse7/fuse-apicurito/manifests/1.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/apicurito-ui><imagestream/jboss-webserver50-tomcat9-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-webserver-5/webserver50-tomcat9-openshift:latest:
        Get
        https://registry.redhat.io/v2/jboss-webserver-5/webserver50-tomcat9-openshift/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-webserver50-tomcat9-openshift><imagestream/redhat-sso70-openshift>Internal
        error occurred: registry.redhat.io/redhat-sso-7/sso70-openshift:1.4: Get
        https://registry.redhat.io/v2/redhat-sso-7/sso70-openshift/manifests/1.4:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/redhat-sso70-openshift><imagestream/jboss-datagrid65-client-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datagrid-6/datagrid65-client-openshift:1.1: Get
        https://registry.redhat.io/v2/jboss-datagrid-6/datagrid65-client-openshift/manifests/1.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datagrid65-client-openshift><imagestream/jboss-amq-62>Internal
        error occurred: registry.redhat.io/jboss-amq-6/amq62-openshift:1.7: Get
        https://registry.redhat.io/v2/jboss-amq-6/amq62-openshift/manifests/1.7:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-amq-62><imagestream/jboss-datagrid72-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datagrid-7/datagrid72-openshift:1.2: Get
        https://registry.redhat.io/v2/jboss-datagrid-7/datagrid72-openshift/manifests/1.2:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datagrid72-openshift><imagestream/postgresql>Internal
        error occurred: registry.redhat.io/rhscl/postgresql-96-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/postgresql-96-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/postgresql><imagestream/jboss-fuse70-console>Internal
        error occurred: registry.redhat.io/fuse7/fuse-console:1.0: Get
        https://registry.redhat.io/v2/fuse7/fuse-console/manifests/1.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-fuse70-console><imagestream/modern-webapp>Internal
        error occurred:
        registry.redhat.io/rhoar-nodejs-tech-preview/rhoar-nodejs-10-webapp:latest:
        Get
        https://registry.redhat.io/v2/rhoar-nodejs-tech-preview/rhoar-nodejs-10-webapp/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/modern-webapp><imagestream/jboss-datavirt64-driver-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datavirt-6/datavirt64-driver-openshift:1.7: Get
        https://registry.redhat.io/v2/jboss-datavirt-6/datavirt64-driver-openshift/manifests/1.7:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datavirt64-driver-openshift><imagestream/fuse7-java-openshift>Internal
        error occurred: registry.redhat.io/fuse7/fuse-java-openshift:1.5: Get
        https://registry.redhat.io/v2/fuse7/fuse-java-openshift/manifests/1.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fuse7-java-openshift><imagestream/redhat-sso71-openshift>Internal
        error occurred: registry.redhat.io/redhat-sso-7/sso71-openshift:1.3: Get
        https://registry.redhat.io/v2/redhat-sso-7/sso71-openshift/manifests/1.3:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/redhat-sso71-openshift><imagestream/fis-karaf-openshift>Internal
        error occurred: registry.redhat.io/jboss-fuse-6/fis-karaf-openshift:2.0:
        Get
        https://registry.redhat.io/v2/jboss-fuse-6/fis-karaf-openshift/manifests/2.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fis-karaf-openshift><imagestream/python>Internal
        error occurred: registry.redhat.io/rhscl/python-36-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/python-36-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/python><imagestream/jboss-fuse70-java-openshift>Internal
        error occurred: registry.redhat.io/fuse7/fuse-java-openshift:1.0: Get
        https://registry.redhat.io/v2/fuse7/fuse-java-openshift/manifests/1.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-fuse70-java-openshift><imagestream/openjdk-11-rhel8>Internal
        error occurred: registry.redhat.io/openjdk/openjdk-11-rhel8:1.1: Get
        https://registry.redhat.io/v2/openjdk/openjdk-11-rhel8/manifests/1.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/openjdk-11-rhel8><imagestream/jboss-eap64-openshift>Internal
        error occurred: registry.redhat.io/jboss-eap-6/eap64-openshift:latest:
        Get
        https://registry.redhat.io/v2/jboss-eap-6/eap64-openshift/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-eap64-openshift><imagestream/fuse7-eap-openshift>Internal
        error occurred: registry.redhat.io/fuse7/fuse-eap-openshift:1.5: Get
        https://registry.redhat.io/v2/fuse7/fuse-eap-openshift/manifests/1.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fuse7-eap-openshift><imagestream/eap-cd-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-eap-7-tech-preview/eap-cd-openshift-rhel8:latest:
        Get
        https://registry.redhat.io/v2/jboss-eap-7-tech-preview/eap-cd-openshift-rhel8/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/eap-cd-openshift><imagestream/fuse7-console>Internal
        error occurred: registry.redhat.io/fuse7/fuse-console:1.5: Get
        https://registry.redhat.io/v2/fuse7/fuse-console/manifests/1.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fuse7-console><imagestream/nodejs>Internal
        error occurred: registry.redhat.io/rhscl/nodejs-12-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/nodejs-12-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/nodejs><imagestream/jboss-datagrid73-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datagrid-7/datagrid73-openshift:1.1: Get
        https://registry.redhat.io/v2/jboss-datagrid-7/datagrid73-openshift/manifests/1.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datagrid73-openshift><imagestream/perl>Internal
        error occurred: registry.redhat.io/rhscl/perl-526-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/perl-526-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/perl><imagestream/rhpam-businesscentral-rhel8>Internal
        error occurred:
        registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.5.1: Get
        https://registry.redhat.io/v2/rhpam-7/rhpam-businesscentral-rhel8/manifests/7.5.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhpam-businesscentral-rhel8><imagestream/jboss-eap71-openshift>Internal
        error occurred: registry.redhat.io/jboss-eap-7/eap71-openshift:latest:
        Get
        https://registry.redhat.io/v2/jboss-eap-7/eap71-openshift/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-eap71-openshift><imagestream/jboss-datagrid65-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datagrid-6/datagrid65-openshift:1.6: Get
        https://registry.redhat.io/v2/jboss-datagrid-6/datagrid65-openshift/manifests/1.6:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datagrid65-openshift><imagestream/fis-java-openshift>Internal
        error occurred: registry.redhat.io/jboss-fuse-6/fis-java-openshift:2.0:
        Get
        https://registry.redhat.io/v2/jboss-fuse-6/fis-java-openshift/manifests/2.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fis-java-openshift><imagestream/redhat-openjdk18-openshift>Internal
        error occurred:
        registry.redhat.io/redhat-openjdk-18/openjdk18-openshift:1.7: Get
        https://registry.redhat.io/v2/redhat-openjdk-18/openjdk18-openshift/manifests/1.7:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/redhat-openjdk18-openshift><imagestream/jboss-decisionserver64-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-decisionserver-6/decisionserver64-openshift:1.6:
        Get
        https://registry.redhat.io/v2/jboss-decisionserver-6/decisionserver64-openshift/manifests/1.6:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-decisionserver64-openshift><imagestream/mysql>Internal
        error occurred: registry.redhat.io/rhscl/mysql-80-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/mysql-80-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/mysql><imagestream/httpd>Internal
        error occurred: registry.redhat.io/rhscl/httpd-24-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/httpd-24-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/httpd><imagestream/openjdk-11-rhel7>Internal
        error occurred: registry.redhat.io/openjdk/openjdk-11-rhel7:1.1: Get
        https://registry.redhat.io/v2/openjdk/openjdk-11-rhel7/manifests/1.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/openjdk-11-rhel7><imagestream/jboss-webserver30-tomcat7-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-webserver-3/webserver30-tomcat7-openshift:1.3:
        Get
        https://registry.redhat.io/v2/jboss-webserver-3/webserver30-tomcat7-openshift/manifests/1.3:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-webserver30-tomcat7-openshift><imagestream/dotnet-runtime>Internal
        error occurred: registry.redhat.io/dotnet/dotnet-31-runtime-rhel7:3.1:
        Get
        https://registry.redhat.io/v2/dotnet/dotnet-31-runtime-rhel7/manifests/3.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/dotnet-runtime><imagestream/dotnet>Internal
        error occurred: registry.redhat.io/dotnet/dotnet-31-rhel7:3.1: Get
        https://registry.redhat.io/v2/dotnet/dotnet-31-rhel7/manifests/3.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/dotnet><imagestream/golang>Internal
        error occurred: registry.redhat.io/devtools/go-toolset-rhel7:1.11.5: Get
        https://registry.redhat.io/v2/devtools/go-toolset-rhel7/manifests/1.11.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/golang><imagestream/rhpam-kieserver-rhel8>Internal
        error occurred: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.5.0:
        Get
        https://registry.redhat.io/v2/rhpam-7/rhpam-kieserver-rhel8/manifests/7.5.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhpam-kieserver-rhel8><imagestream/rhdm-decisioncentral-rhel8>Internal
        error occurred:
        registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.5.1: Get
        https://registry.redhat.io/v2/rhdm-7/rhdm-decisioncentral-rhel8/manifests/7.5.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhdm-decisioncentral-rhel8><imagestream/jboss-fuse70-eap-openshift>Internal
        error occurred: registry.redhat.io/fuse7/fuse-eap-openshift:1.0: Get
        https://registry.redhat.io/v2/fuse7/fuse-eap-openshift/manifests/1.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-fuse70-eap-openshift><imagestream/redhat-sso72-openshift>Internal
        error occurred: registry.redhat.io/redhat-sso-7/sso72-openshift:1.4: Get
        https://registry.redhat.io/v2/redhat-sso-7/sso72-openshift/manifests/1.4:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/redhat-sso72-openshift><imagestream/fuse-apicurito-generator>Internal
        error occurred: registry.redhat.io/fuse7/fuse-apicurito-generator:1.5:
        Get
        https://registry.redhat.io/v2/fuse7/fuse-apicurito-generator/manifests/1.5:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/fuse-apicurito-generator><imagestream/rhpam-smartrouter-rhel8>Internal
        error occurred:
        registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.5.1: Get
        https://registry.redhat.io/v2/rhpam-7/rhpam-smartrouter-rhel8/manifests/7.5.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhpam-smartrouter-rhel8><imagestream/jboss-fuse70-karaf-openshift>Internal
        error occurred: registry.redhat.io/fuse7/fuse-karaf-openshift:1.0: Get
        https://registry.redhat.io/v2/fuse7/fuse-karaf-openshift/manifests/1.0:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-fuse70-karaf-openshift><imagestream/openjdk-8-rhel8>Internal
        error occurred: registry.redhat.io/openjdk/openjdk-8-rhel8:1.1: Get
        https://registry.redhat.io/v2/openjdk/openjdk-8-rhel8/manifests/1.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/openjdk-8-rhel8><imagestream/rhdm-kieserver-rhel8>Internal
        error occurred: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.5.1:
        Get
        https://registry.redhat.io/v2/rhdm-7/rhdm-kieserver-rhel8/manifests/7.5.1:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/rhdm-kieserver-rhel8><imagestream/jboss-datavirt64-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-datavirt-6/datavirt64-openshift:1.7: Get
        https://registry.redhat.io/v2/jboss-datavirt-6/datavirt64-openshift/manifests/1.7:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-datavirt64-openshift><imagestream/jboss-processserver64-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-processserver-6/processserver64-openshift:1.6:
        Get
        https://registry.redhat.io/v2/jboss-processserver-6/processserver64-openshift/manifests/1.6:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-processserver64-openshift><imagestream/ruby>Internal
        error occurred: registry.redhat.io/rhscl/ruby-25-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/ruby-25-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/ruby><imagestream/apicast-gateway>Internal
        error occurred:
        registry.redhat.io/3scale-amp2/apicast-gateway-rhel7:3scale2.7: Get
        https://registry.redhat.io/v2/3scale-amp2/apicast-gateway-rhel7/manifests/3scale2.7:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/apicast-gateway><imagestream/jboss-webserver30-tomcat8-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-webserver-3/webserver30-tomcat8-openshift:1.3:
        Get
        https://registry.redhat.io/v2/jboss-webserver-3/webserver30-tomcat8-openshift/manifests/1.3:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-webserver30-tomcat8-openshift><imagestream/jboss-webserver31-tomcat7-openshift>Internal
        error occurred:
        registry.redhat.io/jboss-webserver-3/webserver31-tomcat7-openshift:1.4:
        Get
        https://registry.redhat.io/v2/jboss-webserver-3/webserver31-tomcat7-openshift/manifests/1.4:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/jboss-webserver31-tomcat7-openshift><imagestream/nginx>Internal
        error occurred: registry.redhat.io/rhscl/nginx-114-rhel7:latest: Get
        https://registry.redhat.io/v2/rhscl/nginx-114-rhel7/manifests/latest:
        unauthorized: Please login to the Red Hat Registry using your Customer
        Portal credentials. Further instructions can be found here:
        https://access.redhat.com/RegistryAuthentication<imagestream/nginx>
      reason: >-
        jboss-eap72-openshift redhat-sso73-openshift java
        rhdm-optaweb-employee-rostering-rhel8 jboss-datagrid71-client-openshift
        php jboss-eap70-openshift redis jboss-amq-63
        rhpam-businesscentral-monitoring-rhel8 mongodb
        jboss-datagrid71-openshift fuse7-karaf-openshift
        jboss-webserver31-tomcat8-openshift mariadb apicurito-ui
        jboss-webserver50-tomcat9-openshift redhat-sso70-openshift
        jboss-datagrid65-client-openshift jboss-amq-62
        jboss-datagrid72-openshift postgresql jboss-fuse70-console modern-webapp
        jboss-datavirt64-driver-openshift fuse7-java-openshift
        redhat-sso71-openshift fis-karaf-openshift python
        jboss-fuse70-java-openshift openjdk-11-rhel8 jboss-eap64-openshift
        fuse7-eap-openshift eap-cd-openshift fuse7-console nodejs
        jboss-datagrid73-openshift perl rhpam-businesscentral-rhel8
        jboss-eap71-openshift jboss-datagrid65-openshift fis-java-openshift
        redhat-openjdk18-openshift jboss-decisionserver64-openshift mysql httpd
        openjdk-11-rhel7 jboss-webserver30-tomcat7-openshift dotnet-runtime
        dotnet golang rhpam-kieserver-rhel8 rhdm-decisioncentral-rhel8
        jboss-fuse70-eap-openshift redhat-sso72-openshift
        fuse-apicurito-generator rhpam-smartrouter-rhel8
        jboss-fuse70-karaf-openshift openjdk-8-rhel8 rhdm-kieserver-rhel8
        jboss-datavirt64-openshift jboss-processserver64-openshift ruby
        apicast-gateway jboss-webserver30-tomcat8-openshift
        jboss-webserver31-tomcat7-openshift nginx 
      status: 'True'
      type: ImportImageErrorsExist
    - lastTransitionTime: '2020-04-22T14:42:49Z'
      lastUpdateTime: '2020-04-22T14:42:49Z'
      status: 'False'
      type: ImageChangesInProgress
    - lastTransitionTime: '2020-04-22T14:41:46Z'
      lastUpdateTime: '2020-04-22T14:41:46Z'
      status: 'True'
      type: SamplesExist
    - lastTransitionTime: '2020-04-22T14:41:43Z'
      lastUpdateTime: '2020-04-22T14:41:43Z'
      status: 'False'
      type: RemovePending
    - lastTransitionTime: '2020-04-22T14:41:43Z'
      lastUpdateTime: '2020-04-22T14:41:43Z'
      status: 'False'
      type: MigrationInProgress
  managementState: Managed
  version: 4.4.0-0.okd-2020-04-21-163702-beta4
```

**Comment by sapkra** [comment]
Same here. My cluster update to beta 5 is failing because of this problem I think.

![image](https://user-images.githubusercontent.com/8087568/82887404-3d1d1800-9f48-11ea-845e-eb63748ab3d2.png)

![image](https://user-images.githubusercontent.com/8087568/82887362-2f679280-9f48-11ea-9ef1-21cce53b3bc3.png)

![image](https://user-images.githubusercontent.com/8087568/82887775-c6344f00-9f48-11ea-8983-a4526b6e6f0a.png)

**Comment by ibotty** [comment]
Any Idea on when this can be fixed?

**Comment by vrutkovs** [comment]
This is resolved in 4.6 nightlies. Lets keep this open until 4.6 is promoted to stable, as release notes would require some update and more update testing is required

**Comment by ibotty** [comment]
Cool!  Thank you for fixing it.

**Comment by sandrobonazzola** [comment]
Confirming issue is still there in Version 4.5.0-0.okd-2020-10-15-235428, looking forward for 4.6 to be promoted to stable.

**Comment by vrutkovs** [comment]
OKD 4.6 now uses CentOS/UBI imagestreams

**Comment by ibotty** [comment]
Can you point to docs on updating an existing cluster to use the new imagestreams?  I could not find the release notes mentioning it.

**Comment by vrutkovs** [comment]
It was part of https://github.com/openshift/release/pull/10491, no action necessary
